/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.ImageIcon;
import model.bean.Sessao;

/**
 *
 * @author Jefferson Bruno de Assis Lima José Cláudio de Figueiredo Filho
 * Rodrigo Ferreira Rodrigues
 *
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        permissoesUsuario();
    }

    /**
     *
     * Método que verifica o tipo de usuário que está logado no sistema,
     * alterando o título da janela e bloqueando o acesso às funções de inclusão
     * e exclusão de usuários.
     *
     */
    public void permissoesUsuario() {
        Sessao sessao = Sessao.getInstance();
        this.setTitle("Projeto SegInfo - usuário logado: " + sessao.getUsuario().getNome() + " tipo: " + sessao.getUsuario().getIdentificador());
        if (sessao.getUsuario().getIdentificador().equals("comum")) {
            jMenuItemUsuariosCadastra.setVisible(false);
            jMenuItemExclui.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLogin = new javax.swing.JMenu();
        jMenuItemLoginLogout = new javax.swing.JMenuItem();
        jMenuItemLoginSair = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemUsuariosCadastra = new javax.swing.JMenuItem();
        jMenuItemUsuariosConsulta = new javax.swing.JMenuItem();
        jMenuItemUsuariosAltera = new javax.swing.JMenuItem();
        jMenuItemExclui = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemSobreSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto de segurança da Informação");
        setIconImage(new ImageIcon(getClass().getResource("/Imagens/icon.png")).getImage());

        jDesktopPane.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jMenuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/connect.png"))); // NOI18N
        jMenuLogin.setText("Login");
        jMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoginActionPerformed(evt);
            }
        });

        jMenuItemLoginLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/disconnect.png"))); // NOI18N
        jMenuItemLoginLogout.setText("Logout / Troca Usuário");
        jMenuItemLoginLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginLogoutActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuItemLoginLogout);

        jMenuItemLoginSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/exit_power.png"))); // NOI18N
        jMenuItemLoginSair.setText("Sair");
        jMenuItemLoginSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginSairActionPerformed(evt);
            }
        });
        jMenuLogin.add(jMenuItemLoginSair);

        jMenuBar1.add(jMenuLogin);

        jMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jMenuUsuarios.setText("Usuários");

        jMenuItemUsuariosCadastra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jMenuItemUsuariosCadastra.setText("Cadastrar");
        jMenuItemUsuariosCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosCadastraActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUsuariosCadastra);

        jMenuItemUsuariosConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItemUsuariosConsulta.setText("Consultar");
        jMenuItemUsuariosConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosConsultaActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUsuariosConsulta);

        jMenuItemUsuariosAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        jMenuItemUsuariosAltera.setText("Altera");
        jMenuItemUsuariosAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosAlteraActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUsuariosAltera);

        jMenuItemExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        jMenuItemExclui.setText("Excluir");
        jMenuItemExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluiActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemExclui);

        jMenuBar1.add(jMenuUsuarios);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/help.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });

        jMenuItemSobreSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/help.png"))); // NOI18N
        jMenuItemSobreSobre.setText("Sobre o programa");
        jMenuItemSobreSobre.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuItemSobreSobreAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenuItemSobreSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreSobreActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItemSobreSobre);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSobreSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreSobreActionPerformed
        Sobre frame = new Sobre();
        jDesktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreSobreActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void jMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLoginActionPerformed

    private void jMenuItemLoginSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemLoginSairActionPerformed

    private void jMenuItemSobreSobreAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuItemSobreSobreAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSobreSobreAncestorAdded

    private void jMenuItemUsuariosCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosCadastraActionPerformed
        Cadastro frame = new Cadastro();
        jDesktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosCadastraActionPerformed

    private void jMenuItemUsuariosConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosConsultaActionPerformed
        Consulta frame = new Consulta();
        jDesktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosConsultaActionPerformed

    private void jMenuItemUsuariosAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosAlteraActionPerformed
        Altera frame = new Altera();
        jDesktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosAlteraActionPerformed

    private void jMenuItemExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluiActionPerformed
        Exclui frame = new Exclui();
        jDesktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluiActionPerformed

    private void jMenuItemLoginLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginLogoutActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLoginLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemExclui;
    private javax.swing.JMenuItem jMenuItemLoginLogout;
    private javax.swing.JMenuItem jMenuItemLoginSair;
    private javax.swing.JMenuItem jMenuItemSobreSobre;
    private javax.swing.JMenuItem jMenuItemUsuariosAltera;
    private javax.swing.JMenuItem jMenuItemUsuariosCadastra;
    private javax.swing.JMenuItem jMenuItemUsuariosConsulta;
    private javax.swing.JMenu jMenuLogin;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenu jMenuUsuarios;
    // End of variables declaration//GEN-END:variables

}
